name: Test Environment Vars
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    environment: development   # IMPORTANT

    steps:
      - name: Echo env var
        run: echo "Node env is: ${{ vars.NODE_ENV }}"
